from __future__ import annotations

FAMILY_ANOMALY_REGISTRY: dict[str, dict] = {
    "price_velocity": {
        "indicator_name": "price_velocity",
        "indicator_family": "family_anomaly",
        "version": "v1",
        "definition": "Measure short-term market probability velocity.",
        "formula": "abs(current_market_probability - previous_market_probability) / delta_time",
        "input_contracts": ["MarketSnapshot", "ProbabilityState", "ComparisonPoint"],
        "output_fields": ["price_velocity", "price_velocity_bucket"],
        "applicable_families": ["*"],
        "threshold_policy_ref": "threshold_policy.price_velocity.default.v1",
        "status": "active",
        "owner": "monitoring_layer",
    },
    "edge_dislocation": {
        "indicator_name": "edge_dislocation",
        "indicator_family": "family_anomaly",
        "version": "v1",
        "definition": "Measure distance between fair value and market implied probability.",
        "formula": "abs(fair_value - market_implied_probability)",
        "input_contracts": ["MarketSnapshot", "ProbabilityState", "ComparisonPoint"],
        "output_fields": ["edge_dislocation", "confidence_adjusted_edge_dislocation"],
        "applicable_families": ["*"],
        "threshold_policy_ref": "threshold_policy.edge_dislocation.default.v1",
        "status": "active",
        "owner": "monitoring_layer",
    },
    "evidence_mismatch": {
        "indicator_name": "evidence_mismatch",
        "indicator_family": "family_anomaly",
        "version": "v1",
        "definition": "Detect whether market move and evidence move disagree.",
        "formula": "sign(market_move) != sign(evidence_move)",
        "input_contracts": ["MarketSnapshot", "ForecastSnapshot", "ObservationSnapshot", "ComparisonPoint"],
        "output_fields": ["evidence_mismatch", "evidence_mismatch_score"],
        "applicable_families": ["*"],
        "threshold_policy_ref": "threshold_policy.evidence_mismatch.default.v1",
        "status": "active",
        "owner": "monitoring_layer",
    },
    "microstructure_stress": {
        "indicator_name": "microstructure_stress",
        "indicator_family": "family_anomaly",
        "version": "v1",
        "definition": "Assess spread, liquidity and sidedness stress in market structure.",
        "formula": "weighted mix of spread_jump, liquidity_drop, one_sided_pressure and favored_side_flip_frequency",
        "input_contracts": ["MarketSnapshot"],
        "output_fields": [
            "spread_jump",
            "liquidity_drop",
            "one_sided_pressure",
            "favored_side_flip_frequency",
            "microstructure_stress_score",
        ],
        "applicable_families": ["*"],
        "threshold_policy_ref": "threshold_policy.microstructure_stress.default.v1",
        "status": "active",
        "owner": "monitoring_layer",
    },
    "peer_relative_anomaly": {
        "indicator_name": "peer_relative_anomaly",
        "indicator_family": "family_anomaly",
        "version": "v1",
        "definition": "Measure how far a market is from same-family peers.",
        "formula": "peer z-score over same family / location / date / variable group",
        "input_contracts": ["MarketSnapshot", "ProbabilityState", "ComparisonPoint"],
        "output_fields": ["peer_rank", "peer_zscore", "peer_outlier_flag"],
        "applicable_families": ["*"],
        "threshold_policy_ref": "threshold_policy.peer_relative_anomaly.default.v1",
        "status": "active",
        "owner": "monitoring_layer",
    },
    "intervention_like_score": {
        "indicator_name": "intervention_like_score",
        "indicator_family": "family_anomaly",
        "version": "v1",
        "definition": "Composite anomaly score for intervention-like markets.",
        "formula": "weighted mix of price_velocity, microstructure_stress, evidence_mismatch and peer anomaly",
        "input_contracts": ["MarketSnapshot", "ProbabilityState", "ComparisonPoint", "ForecastSnapshot", "ObservationSnapshot"],
        "output_fields": ["intervention_like_score", "intervention_like_flag"],
        "applicable_families": ["*"],
        "threshold_policy_ref": "threshold_policy.intervention_like_score.default.v1",
        "status": "active",
        "owner": "monitoring_layer",
    },
}


def get_family_anomaly_indicator_definition(indicator_name: str) -> dict:
    return dict(FAMILY_ANOMALY_REGISTRY[indicator_name])
