from __future__ import annotations

OBSERVATION_ALERT_REGISTRY: dict[str, dict] = {
    "observation_shock": {
        "indicator_name": "observation_shock",
        "indicator_family": "observation_alert",
        "version": "v1",
        "definition": "Detect whether observation changes sharply within a short time window.",
        "formula": "shock_delta = current_observation_value - previous_observation_value; shock_slope = shock_delta / delta_time_minutes",
        "input_contracts": ["ObservationSnapshot", "ResolvedMarketRule"],
        "output_fields": [
            "threshold_cross_event",
            "threshold_cross_direction",
            "shock_delta_value",
            "shock_delta_abs",
            "shock_slope_per_minute",
        ],
        "applicable_families": [
            "temperature_daily_max",
            "temperature_daily_min",
            "weather_metric.precipitation",
            "weather_metric.wind_speed",
            "weather_metric.snowfall",
        ],
        "threshold_policy_ref": "threshold_policy.observation_shock.default.v1",
        "requires_exact_station": True,
        "requires_fresh_inputs": True,
        "severity_mapping": {
            "watch": "low shock",
            "amber": "threshold cross or large shock",
            "red": "threshold cross + market lag",
        },
        "status": "active",
        "owner": "monitoring_layer",
        "notes": "Degrade to review-only when source_match_grade != exact_station.",
    },
    "forecast_divergence": {
        "indicator_name": "forecast_divergence",
        "indicator_family": "observation_alert",
        "version": "v1",
        "definition": "Measure divergence between observation and forecast / model snapshot.",
        "formula": "value_divergence = observation_value - forecast_value",
        "input_contracts": ["ObservationSnapshot", "ForecastSnapshot", "ResolvedMarketRule"],
        "output_fields": [
            "value_divergence",
            "value_divergence_abs",
            "band_divergence",
            "band_distance",
            "forecast_divergence_score",
        ],
        "applicable_families": [
            "temperature_daily_max",
            "temperature_daily_min",
            "weather_metric.precipitation",
            "weather_metric.wind_speed",
            "weather_metric.snowfall",
            "global_temperature_index",
            "sea_ice_extent",
        ],
        "threshold_policy_ref": "threshold_policy.forecast_divergence.default.v1",
        "requires_exact_station": False,
        "requires_fresh_inputs": True,
        "status": "active",
        "owner": "monitoring_layer",
        "notes": "Comparison must be contract-aligned by market_id, variable_name, target_date, station_id and band scheme.",
    },
    "market_reaction_gap": {
        "indicator_name": "market_reaction_gap",
        "indicator_family": "observation_alert",
        "version": "v1",
        "definition": "Measure whether evidence moved faster than market reaction.",
        "formula": "fair_value_gap = fair_value - market_implied_probability",
        "input_contracts": ["MarketSnapshot", "ProbabilityState", "ComparisonPoint"],
        "output_fields": [
            "fair_value_gap",
            "reaction_lag_score",
            "market_band_mismatch",
        ],
        "applicable_families": [
            "temperature_daily_max",
            "temperature_daily_min",
            "weather_metric.precipitation",
            "weather_metric.wind_speed",
            "weather_metric.snowfall",
            "global_temperature_index",
            "sea_ice_extent",
        ],
        "threshold_policy_ref": "threshold_policy.market_reaction_gap.default.v1",
        "requires_exact_station": False,
        "requires_fresh_inputs": True,
        "status": "active",
        "owner": "monitoring_layer",
    },
    "resolver_source_risk": {
        "indicator_name": "resolver_source_risk",
        "indicator_family": "observation_alert",
        "version": "v1",
        "definition": "Assess resolver/source contract risk for the current market.",
        "formula": "risk levels are derived from source_match_grade, official_vs_proxy_source and freshness_status",
        "input_contracts": ["ResolvedMarketRule", "ForecastSnapshot", "gate_stack_api.v1"],
        "output_fields": [
            "source_match_risk",
            "officialness_risk",
            "freshness_risk",
        ],
        "applicable_families": [
            "temperature_daily_max",
            "temperature_daily_min",
            "weather_metric.precipitation",
            "weather_metric.wind_speed",
            "weather_metric.snowfall",
            "global_temperature_index",
            "sea_ice_extent",
        ],
        "threshold_policy_ref": "threshold_policy.resolver_source_risk.default.v1",
        "requires_exact_station": False,
        "requires_fresh_inputs": False,
        "status": "active",
        "owner": "monitoring_layer",
    },
    "alert_severity": {
        "indicator_name": "alert_severity",
        "indicator_family": "observation_alert",
        "version": "v1",
        "definition": "Aggregate observation, forecast, market and resolver risk into severity.",
        "formula": "rules-first severity mapping with score assist",
        "input_contracts": ["ObservationSnapshot", "ForecastSnapshot", "MarketSnapshot", "ResolvedMarketRule", "ProbabilityState", "ComparisonPoint"],
        "output_fields": [
            "severity",
            "recommended_operator_action",
            "alert_score",
            "primary_reason",
        ],
        "applicable_families": ["*"],
        "threshold_policy_ref": "threshold_policy.alert_severity.default.v1",
        "requires_exact_station": False,
        "requires_fresh_inputs": False,
        "status": "active",
        "owner": "monitoring_layer",
    },
}


def get_observation_alert_indicator_definition(indicator_name: str) -> dict:
    return dict(OBSERVATION_ALERT_REGISTRY[indicator_name])
