from __future__ import annotations

FAMILY_ANOMALY_POLICIES: dict[str, dict] = {
    "threshold_policy.price_velocity.default.v1": {
        "policy_id": "threshold_policy.price_velocity.default.v1",
        "indicator_name": "price_velocity",
        "family": "*",
        "variable_name": "*",
        "threshold_type": "rule_based",
        "threshold_value": {"price_velocity_bucket": "high"},
        "time_window": "1h",
        "unit": "probability/min",
        "status": "active",
        "version": "v1",
    },
    "threshold_policy.edge_dislocation.default.v1": {
        "policy_id": "threshold_policy.edge_dislocation.default.v1",
        "indicator_name": "edge_dislocation",
        "family": "*",
        "variable_name": "*",
        "threshold_type": "rule_based",
        "threshold_value": {"edge_dislocation_abs": 0.1},
        "time_window": "1h",
        "unit": "probability",
        "status": "active",
        "version": "v1",
    },
    "threshold_policy.evidence_mismatch.default.v1": {
        "policy_id": "threshold_policy.evidence_mismatch.default.v1",
        "indicator_name": "evidence_mismatch",
        "family": "*",
        "variable_name": "*",
        "threshold_type": "rule_based",
        "threshold_value": {"evidence_mismatch_score": 1},
        "time_window": "1h",
        "unit": "score",
        "status": "active",
        "version": "v1",
    },
    "threshold_policy.microstructure_stress.default.v1": {
        "policy_id": "threshold_policy.microstructure_stress.default.v1",
        "indicator_name": "microstructure_stress",
        "family": "*",
        "variable_name": "*",
        "threshold_type": "rule_based",
        "threshold_value": {"microstructure_stress_score": 0.7},
        "time_window": "1h",
        "unit": "score",
        "status": "active",
        "version": "v1",
    },
    "threshold_policy.peer_relative_anomaly.default.v1": {
        "policy_id": "threshold_policy.peer_relative_anomaly.default.v1",
        "indicator_name": "peer_relative_anomaly",
        "family": "*",
        "variable_name": "*",
        "threshold_type": "rule_based",
        "threshold_value": {"peer_zscore": 2.0},
        "time_window": "1d",
        "unit": "zscore",
        "status": "active",
        "version": "v1",
    },
    "threshold_policy.intervention_like_score.default.v1": {
        "policy_id": "threshold_policy.intervention_like_score.default.v1",
        "indicator_name": "intervention_like_score",
        "family": "*",
        "variable_name": "*",
        "threshold_type": "rule_based",
        "threshold_value": {"intervention_like_score": 0.8},
        "time_window": "1d",
        "unit": "score",
        "status": "active",
        "version": "v1",
    },
}


def get_family_anomaly_threshold_policy(policy_id: str) -> dict:
    return dict(FAMILY_ANOMALY_POLICIES[policy_id])
