from __future__ import annotations

OBSERVATION_ALERT_POLICIES: dict[str, dict] = {
    "threshold_policy.observation_shock.default.v1": {
        "policy_id": "threshold_policy.observation_shock.default.v1",
        "indicator_name": "observation_shock",
        "family": "*",
        "variable_name": "*",
        "threshold_type": "rule_based",
        "threshold_value": {
            "shock_delta_abs": 0.3,
            "shock_slope_per_minute": 0.02,
            "threshold_cross_event": True,
        },
        "time_window": "15m",
        "unit": "native",
        "severity_rules": {
            "watch": {"shock_delta_abs_gte": 0.2},
            "amber": {"shock_delta_abs_gte": 0.3},
            "red": {"threshold_cross_event": True, "requires_market_lag": True},
        },
        "freshness_required": "fresh",
        "source_match_required": "exact_station",
        "status": "active",
        "version": "v1",
        "notes": "Use review-only downgrade when official_vs_proxy_source != official.",
    },
    "threshold_policy.forecast_divergence.default.v1": {
        "policy_id": "threshold_policy.forecast_divergence.default.v1",
        "indicator_name": "forecast_divergence",
        "family": "*",
        "variable_name": "*",
        "threshold_type": "rule_based",
        "threshold_value": {"value_divergence_abs": 0.3},
        "time_window": "1h",
        "unit": "native",
        "severity_rules": {
            "watch": {"value_divergence_abs_gte": 0.2},
            "amber": {"value_divergence_abs_gte": 0.3},
            "red": {"value_divergence_abs_gte": 0.5},
        },
        "freshness_required": "fresh",
        "source_match_required": "family_exact",
        "status": "active",
        "version": "v1",
        "notes": "Comparison must be contract aligned.",
    },
    "threshold_policy.market_reaction_gap.default.v1": {
        "policy_id": "threshold_policy.market_reaction_gap.default.v1",
        "indicator_name": "market_reaction_gap",
        "family": "*",
        "variable_name": "*",
        "threshold_type": "rule_based",
        "threshold_value": {"fair_value_gap_abs": 0.1},
        "time_window": "1h",
        "unit": "probability",
        "severity_rules": {
            "watch": {"fair_value_gap_abs_gte": 0.05},
            "amber": {"fair_value_gap_abs_gte": 0.1},
            "red": {"fair_value_gap_abs_gte": 0.15},
        },
        "freshness_required": "fresh_or_stale",
        "source_match_required": "family_exact",
        "status": "active",
        "version": "v1",
    },
    "threshold_policy.resolver_source_risk.default.v1": {
        "policy_id": "threshold_policy.resolver_source_risk.default.v1",
        "indicator_name": "resolver_source_risk",
        "family": "*",
        "variable_name": "*",
        "threshold_type": "rule_based",
        "threshold_value": {"source_match_grade": ["exact_station", "family_exact"]},
        "time_window": "n/a",
        "unit": "grade",
        "severity_rules": {
            "watch": {"source_match_grade": "family_exact"},
            "amber": {"source_match_grade": "family_only"},
            "red": {"source_match_grade": "unmatched"},
        },
        "freshness_required": "fresh_or_stale",
        "source_match_required": "family_exact",
        "status": "active",
        "version": "v1",
    },
    "threshold_policy.alert_severity.default.v1": {
        "policy_id": "threshold_policy.alert_severity.default.v1",
        "indicator_name": "alert_severity",
        "family": "*",
        "variable_name": "*",
        "threshold_type": "rule_based",
        "threshold_value": {"severity": ["info", "watch", "amber", "red"]},
        "time_window": "n/a",
        "unit": "severity",
        "severity_rules": {
            "info": {"signals": []},
            "watch": {"signals": ["low shock"]},
            "amber": {"signals": ["threshold cross", "divergence", "lag"]},
            "red": {"signals": ["fresh exact-station threshold cross + lag"]},
        },
        "freshness_required": "fresh_or_stale",
        "source_match_required": "family_exact",
        "status": "active",
        "version": "v1",
    },
}


def get_observation_alert_threshold_policy(policy_id: str) -> dict:
    return dict(OBSERVATION_ALERT_POLICIES[policy_id])
